{{- if .Values.datadog.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "test-devops-app.fullname" . }}-datadog
  labels:
    app: datadog-agent
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
{{- end }}

