{{- if .Values.datadog.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "test-devops-app.fullname" . }}-datadog-secret
  labels:
    app: datadog-agent
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  {{- if .Values.datadog.apiKey }}
  api-key: {{ .Values.datadog.apiKey | b64enc | quote }}
  {{- else }}
  api-key: ""
  {{- end }}
{{- end }}

