{{- if and .Values.datadog.enabled (not .Values.vault.enabled) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "test-devops-app.fullname" . }}-datadog
  labels:
    {{- include "test-devops-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: datadog-agent
{{- end }}

