app:
  replicaCount: 2
  image:
    tag: "latest" # CI จะ update ค่านี้
  env:
    nodeEnv: staging
  resources:
    limits:
      cpu: 200m
      memory: 256Mi

graphite:
  persistence:
    enabled: true
    size: 1Gi
