app:
  replicaCount: 3
  image:
    tag: "latest" # CI ‡∏à‡∏∞ update ‡∏Ñ‡πà‡∏≤‡∏ô‡∏µ‡πâ
  env:
    nodeEnv: production
  resources:
    limits:
      cpu: 500m
      memory: 512Mi

graphite:
  persistence:
    enabled: true
    size: 10Gi
    storageClass: "gp2" # üëà ‡∏™‡∏≥‡∏Ñ‡∏±‡∏ç: ‡∏ä‡∏∑‡πà‡∏≠ Storage Class ‡∏Ç‡∏≠‡∏á AWS EBS

# ‡∏ñ‡πâ‡∏≤‡∏°‡∏µ Ingress (‡πÉ‡∏ä‡πâ ALB Controller)
ingress:
  enabled: true
  className: "alb"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing