app:
  replicaCount: 3
  image:
    tag: "latest" # CI à¸ˆà¸° update à¸„à¹ˆà¸²à¸™à¸µà¹‰
  env:
    nodeEnv: production
  resources:
    limits:
      cpu: 500m
      memory: 512Mi

graphite:
  persistence:
    enabled: true
    size: 10Gi
    storageClass: "standard-rwo" # ğŸ‘ˆ à¸ªà¸³à¸„à¸±à¸: à¸Šà¸·à¹ˆà¸­ Storage Class à¸‚à¸­à¸‡ GKE

# à¸–à¹‰à¸²à¸¡à¸µ Ingress
ingress:
  enabled: true
  className: "gce" # à¸«à¸£à¸·à¸­ nginx
  annotations:
    kubernetes.io/ingress.class: "gce"